#minimun config for fsh only
id: fhir.who.immunization
name: who-smart-immunizations
status: draft
version: 0.1.0
fhirVersion: 4.0.1
FSHOnly: true
copyrightYear: 2021+
# temp canonical
canonical: http://fhir.org/guides/who/smart-immunization/ImplementationGuide/fhir.who.immunization

dependencies:
  hl7.fhir.uv.ips: 1.0.0
  # must use local cache version, builds are not on https://build.fhir.org/ig/qas.json